# Generated by Django 4.1.7 on 2023-02-18 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_managers_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='email',
            field=models.EmailField(default='andreymazo@mail.ru', max_length=50, verbose_name='Емэйл в форме сабджекта'),
        ),
        migrations.AddField(
            model_name='subject',
            name='email_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.emails'),
        ),
        migrations.AddField(
            model_name='subject',
            name='mssg_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.mssg'),
        ),
        migrations.AddField(
            model_name='subject',
            name='text',
            field=models.CharField(default='and here', max_length=100, verbose_name='Текст сообщения в форме сабджекта'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Емэйл'),
        ),
    ]
