# Generated by Django 4.1.7 on 2023-02-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_subject_email_subject_email_subj_subject_mssg_subj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='email_subj',
            field=models.CharField(max_length=100, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mssg_subj',
            field=models.CharField(max_length=100, verbose_name='Текст сообщения'),
        ),
    ]
