# Generated by Django 4.1.7 on 2023-02-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_subject_email_subj_alter_subject_mssg_subj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='email_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.emails'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='mssg_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.mssg'),
        ),
    ]
