# Generated by Django 4.1.7 on 2023-02-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_subject_email_subj_alter_subject_mssg_subj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='email_subj',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='mssg_subj',
        ),
    ]
