# Generated by Django 4.1.7 on 2023-02-18 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_subject_email_subj_remove_subject_mssg_subj'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='email_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.emails'),
        ),
        migrations.AddField(
            model_name='subject',
            name='mssg_subj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailing.mssg'),
        ),
        migrations.AlterField(
            model_name='mssg',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Тема сообщения'),
        ),
    ]
