# Generated by Django 4.1.7 on 2023-02-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_subject_email_subj_subject_mssg_subj_alter_mssg_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='topic',
            field=models.CharField(default='and here', max_length=100, verbose_name='Тема сообщения в форме сабджекта'),
        ),
    ]
