# Generated by Django 4.1.7 on 2023-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_subject_period_alter_subject_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='new_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='новый пароль'),
        ),
        migrations.AddField(
            model_name='client',
            name='verify_token',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Токен верификации'),
        ),
        migrations.AddField(
            model_name='client',
            name='verify_token_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения токена'),
        ),
    ]
