# Generated by Django 4.1.7 on 2023-03-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_client_new_password_client_verify_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('view_email', 'can view email')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='mssg',
            name='period',
            field=models.IntegerField(blank=True, choices=[(120, 'день=86400'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mssg',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема сообщения'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.IntegerField(choices=[(86400, '3min=120'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], default=86400, max_length=10, verbose_name='Период'),
        ),
    ]
