# Generated by Django 4.1.7 on 2023-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0013_alter_client_options_alter_mssg_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mssg',
            name='period',
            field=models.IntegerField(blank=True, choices=[(120, 'день=120'), (604800, 'неделя=604800'), (2419200, 'месяц=2419200')], max_length=10, null=True),
        ),
    ]
